// Code generated by error_helpers_gen.go; DO NOT EDIT.

package threecommas

func (r *GetCurrencyRatesResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

type GetJSON400 interface {
	JSON400() *BadRequest
}

func (r *GetCurrencyRatesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

type GetJSON401 interface {
	JSON401() *Unauthorized
}

func (r *GetCurrencyRatesResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

type GetJSON403 interface {
	JSON403() *Forbidden
}

func (r *GetCurrencyRatesResponse) GetJSON404() *NotFound {
	return r.JSON404
}

type GetJSON404 interface {
	JSON404() *NotFound
}

func (r *GetCurrencyRatesResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

type GetJSON418 interface {
	JSON418() *IPAutoBanned
}

func (r *GetCurrencyRatesResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

type GetJSON429 interface {
	JSON429() *RateLimitExceeded
}

func (r *GetCurrencyRatesResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

type GetJSON500 interface {
	JSON500() *InternalServerError
}

func (r *GetCurrencyRatesResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

type GetJSON504 interface {
	JSON504() *GatewayTimeout
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetCurrencyRatesWithLeverageDataResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetMarketListResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetMarketListResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetMarketListResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetMarketListResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetMarketListResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetMarketListResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetMarketListResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetMarketListResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetMarketPairsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetMarketPairsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetMarketPairsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetMarketPairsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetMarketPairsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetMarketPairsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetMarketPairsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetMarketPairsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *ListBotsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *ListBotsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *ListBotsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *ListBotsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *ListBotsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *ListBotsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *ListBotsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *ListBotsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *CreateDcaBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *CreateDcaBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *CreateDcaBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *CreateDcaBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *CreateDcaBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *CreateDcaBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *CreateDcaBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *CreateDcaBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetPairsBlacklistResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetPairsBlacklistResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetPairsBlacklistResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetPairsBlacklistResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetPairsBlacklistResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetPairsBlacklistResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetPairsBlacklistResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetPairsBlacklistResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetBotsStatsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetBotsStatsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetBotsStatsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetBotsStatsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetBotsStatsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetBotsStatsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetBotsStatsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetBotsStatsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetBotsStatsByDateResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetBotsStatsByDateResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetBotsStatsByDateResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetBotsStatsByDateResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetBotsStatsByDateResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetBotsStatsByDateResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetBotsStatsByDateResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetBotsStatsByDateResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *ListStrategiesResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *ListStrategiesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *ListStrategiesResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *ListStrategiesResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *ListStrategiesResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *ListStrategiesResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *ListStrategiesResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *ListStrategiesResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *UpdatePairsBlacklistResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *UpdatePairsBlacklistResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *UpdatePairsBlacklistResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *UpdatePairsBlacklistResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *UpdatePairsBlacklistResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *UpdatePairsBlacklistResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *UpdatePairsBlacklistResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *UpdatePairsBlacklistResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *CancelAllDealsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *CancelAllDealsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *CancelAllDealsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *CancelAllDealsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *CancelAllDealsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *CancelAllDealsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *CancelAllDealsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *CancelAllDealsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *CopyAndCreateBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *CopyAndCreateBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *CopyAndCreateBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *CopyAndCreateBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *CopyAndCreateBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *CopyAndCreateBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *CopyAndCreateBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *CopyAndCreateBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetDealsStatsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetDealsStatsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetDealsStatsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetDealsStatsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetDealsStatsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetDealsStatsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetDealsStatsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetDealsStatsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *DeleteBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *DeleteBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *DeleteBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *DeleteBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *DeleteBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *DeleteBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *DeleteBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *DeleteBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *DisableBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *DisableBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *DisableBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *DisableBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *DisableBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *DisableBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *DisableBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *DisableBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *EnableBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *EnableBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *EnableBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *EnableBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *EnableBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *EnableBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *EnableBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *EnableBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *PanicSellAllDealsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *PanicSellAllDealsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *PanicSellAllDealsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *PanicSellAllDealsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *PanicSellAllDealsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *PanicSellAllDealsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *PanicSellAllDealsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *PanicSellAllDealsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetProfitByDayResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetProfitByDayResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetProfitByDayResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetProfitByDayResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetProfitByDayResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetProfitByDayResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetProfitByDayResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetProfitByDayResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *UpdateBotResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *UpdateBotResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *UpdateBotResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *UpdateBotResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *UpdateBotResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *UpdateBotResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *UpdateBotResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *UpdateBotResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *ListDealsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *ListDealsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *ListDealsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *ListDealsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *ListDealsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *ListDealsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *ListDealsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *ListDealsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *CancelDealResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *CancelDealResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *CancelDealResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *CancelDealResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *CancelDealResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *CancelDealResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *CancelDealResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *CancelDealResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetDealDataForAddingFundsResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetDealDataForAddingFundsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetDealDataForAddingFundsResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetDealDataForAddingFundsResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetDealDataForAddingFundsResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetDealDataForAddingFundsResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetDealDataForAddingFundsResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetDealDataForAddingFundsResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetTradesOfDealResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetTradesOfDealResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetTradesOfDealResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetTradesOfDealResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetTradesOfDealResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetTradesOfDealResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetTradesOfDealResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetTradesOfDealResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *PanicSellDealResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *PanicSellDealResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *PanicSellDealResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *PanicSellDealResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *PanicSellDealResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *PanicSellDealResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *PanicSellDealResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *PanicSellDealResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *PanicSellDealStepResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *PanicSellDealStepResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *PanicSellDealStepResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *PanicSellDealStepResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *PanicSellDealStepResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *PanicSellDealStepResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *PanicSellDealStepResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *PanicSellDealStepResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *GetDealResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *GetDealResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *GetDealResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *GetDealResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *GetDealResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *GetDealResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *GetDealResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *GetDealResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *UpdateDealResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *UpdateDealResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *UpdateDealResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *UpdateDealResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *UpdateDealResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *UpdateDealResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *UpdateDealResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *UpdateDealResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

func (r *ValidateAuthenticationResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

func (r *ValidateAuthenticationResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

func (r *ValidateAuthenticationResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

func (r *ValidateAuthenticationResponse) GetJSON404() *NotFound {
	return r.JSON404
}

func (r *ValidateAuthenticationResponse) GetJSON418() *IPAutoBanned {
	return r.JSON418
}

func (r *ValidateAuthenticationResponse) GetJSON429() *RateLimitExceeded {
	return r.JSON429
}

func (r *ValidateAuthenticationResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

func (r *ValidateAuthenticationResponse) GetJSON504() *GatewayTimeout {
	return r.JSON504
}

type APIErrorResponses interface {
	StatusCode() int
	GetJSON404() *NotFound
	GetJSON418() *IPAutoBanned
	GetJSON429() *RateLimitExceeded
	GetJSON500() *InternalServerError
	GetJSON504() *GatewayTimeout
	GetJSON400() *BadRequest
	GetJSON401() *Unauthorized
	GetJSON403() *Forbidden
}

